// proto/killswitch.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/killswitch.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KillSwitchService_TerminateSession_FullMethodName   = "/killswitch.KillSwitchService/TerminateSession"
	KillSwitchService_ListActiveSessions_FullMethodName = "/killswitch.KillSwitchService/ListActiveSessions"
)

// KillSwitchServiceClient is the client API for KillSwitchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KillSwitchServiceClient interface {
	// TerminateSession forcefully closes the named session's TCP sockets.
	TerminateSession(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error)
	// ListActiveSessions returns all sessions on this proxy node (for dashboard polling).
	ListActiveSessions(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type killSwitchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKillSwitchServiceClient(cc grpc.ClientConnInterface) KillSwitchServiceClient {
	return &killSwitchServiceClient{cc}
}

func (c *killSwitchServiceClient) TerminateSession(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateResponse)
	err := c.cc.Invoke(ctx, KillSwitchService_TerminateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *killSwitchServiceClient) ListActiveSessions(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, KillSwitchService_ListActiveSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KillSwitchServiceServer is the server API for KillSwitchService service.
// All implementations must embed UnimplementedKillSwitchServiceServer
// for forward compatibility.
type KillSwitchServiceServer interface {
	// TerminateSession forcefully closes the named session's TCP sockets.
	TerminateSession(context.Context, *TerminateRequest) (*TerminateResponse, error)
	// ListActiveSessions returns all sessions on this proxy node (for dashboard polling).
	ListActiveSessions(context.Context, *ListRequest) (*ListResponse, error)
	mustEmbedUnimplementedKillSwitchServiceServer()
}

// UnimplementedKillSwitchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKillSwitchServiceServer struct{}

func (UnimplementedKillSwitchServiceServer) TerminateSession(context.Context, *TerminateRequest) (*TerminateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateSession not implemented")
}
func (UnimplementedKillSwitchServiceServer) ListActiveSessions(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActiveSessions not implemented")
}
func (UnimplementedKillSwitchServiceServer) mustEmbedUnimplementedKillSwitchServiceServer() {}
func (UnimplementedKillSwitchServiceServer) testEmbeddedByValue()                           {}

// UnsafeKillSwitchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KillSwitchServiceServer will
// result in compilation errors.
type UnsafeKillSwitchServiceServer interface {
	mustEmbedUnimplementedKillSwitchServiceServer()
}

func RegisterKillSwitchServiceServer(s grpc.ServiceRegistrar, srv KillSwitchServiceServer) {
	// If the following call panics, it indicates UnimplementedKillSwitchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KillSwitchService_ServiceDesc, srv)
}

func _KillSwitchService_TerminateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KillSwitchServiceServer).TerminateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KillSwitchService_TerminateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KillSwitchServiceServer).TerminateSession(ctx, req.(*TerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KillSwitchService_ListActiveSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KillSwitchServiceServer).ListActiveSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KillSwitchService_ListActiveSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KillSwitchServiceServer).ListActiveSessions(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KillSwitchService_ServiceDesc is the grpc.ServiceDesc for KillSwitchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KillSwitchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "killswitch.KillSwitchService",
	HandlerType: (*KillSwitchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TerminateSession",
			Handler:    _KillSwitchService_TerminateSession_Handler,
		},
		{
			MethodName: "ListActiveSessions",
			Handler:    _KillSwitchService_ListActiveSessions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/killswitch.proto",
}
